### ISSUE TITLE
How to specify country in postcode search

### ISSUE THREAD

**Issue by dotsproject** [bensquire/postcodeanywhere-php-api#1]
@bensquire 

I had a look in your code and one script  has been created to search the address on basis of postcode, but here country is not specified. that's why i want to know , how can we specify the country with the post code to narrow the list down of address ,falling  within a postcode of a  specific country.

Any suggestion or code will be helpful to me.
Looking forward to hear from you.

Thanks

**Comment by bensquire** [comment]
Truthfully I'm not sure this was 
  a) considered or
  b) existed as functionality in the API

I've not looked at this code in over 4 years nor the service and I'd be surprised if it still works. If you find it does and are able to adjust the code to accept a country code, please feel free to submit a pull request.

Thanks
